name: sticker_import
description: VK to TG Sticker Import
version: 2.0.1+11
publish_to: none

environment:
    sdk: ">=3.0.0 <4.0.0"

platforms:
    android:

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    intl: ^0.18.1
    vkget:
        git:
            url: https://github.com/Sominemo/VkGet.git
            path: vkget
    fluttertoast: ^8.2.2
    package_info_plus: ^4.2.0
    url_launcher: ^6.2.1
    path_provider: ^2.1.1
    path: ^1.8.1
    enough_convert: ^1.4.0
    device_info_plus: ^9.1.0
    idb_sqflite: ^1.3.2
    sqflite: ^2.3.0
    share_plus: ^7.2.1
    cross_file: ^0.3.3+2

dev_dependencies:
    flutter_lints: ^3.0.0
    intl_utils: ^2.8.5

flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/
        - vkscript/
    fonts:
        - family: Open Sans
          fonts:
              - asset: fonts/OpenSans-SemiBold.ttf
                weight: 600
        - family: CustomIcons
          fonts:
              - asset: fonts/CustomIcons.ttf
                weight: 600
        # Generated with https://github.com/samuelngs/apple-emoji-linux
        # Change the line in Makefile to compress the assets:
        # @convert $(IMOPS) "$<" -adaptive-resize 48x48 -composite "PNG32:$@"
        - family: AppleColorEmoji
          fonts:
              - asset: fonts/AppleColorEmoji.ttf
flutter_intl:
    enabled: true
    main_locale: en
    arb_dir: l10n/

flutter_icons:
    android: true
    image_path: assets/icon-full.png
    adaptive_icon_background: "#FFECED"
    adaptive_icon_foreground: assets/icon.png

flutter_native_splash:
    ios: false
    web: false
    color: "#FFECED"
    image: assets/icon-splash.png
    # branding: assets/branding.png
    color_dark: "#303030"
    image_dark: assets/icon-splash-dark.png
    # branding_dark: assets/branding-dark.png
    android_12:
        image: assets/splash-12.png
        icon_background_color: "#FFECED"
        image_dark: assets/splash-12-dark.png
        icon_background_color_dark: "#303030"
